package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish2020'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish2020")) {
    triggers {
        remove {
            finishBuildTrigger {
                buildType = "SwiftHamcrestAutolayoutMatchers_Build"
                successfulOnly = true
            }
        }
    }
}
